### PR TITLE
Add Completed Project pages

### PR DESCRIPTION
**Pull request by danford1**
### Overview

* edits subtitle on About page
* removes old assets from image folder
* adds fellow profile images and project images
  * fellow profile images follow this naming convention: `firstLast.jpg` (camelcase fellow ID matching the `fellows.yml` file)
  * project images follow this naming convention: `year-nonprofit-name-"featured".jpg` or `year-nonprofit-name-01.jpg`
* adds and edit all Completed Project pages
* adds project card description class to card div (@designmatty see image below; this will require some Design attention, but I used a class called `project-card-description` in `_project-archives/_projects.html` to mimic other card class syntax)
* adds brief_description field to Completed Project page template

screen shot 2018-03-19 at 3 58 25 pm

### CODE REVIEW

**Comment by designmatty** [comment]
Im going to clean this up. I appreciate the descriptions but I wasnt thrilled with how they looked. It's causing some major stretching to cards which is less than ideal. For instance:

screen shot 2018-03-20 at 9 49 28 am

**Comment by designmatty** [comment]
I spent some time squashing your commits and added one for styling the description and fixing broken imagery.

**Comment by designmatty** [comment]
I'm still not thrilled with the stretching cards, but we can come up with a solution later.

**Comment by danford1** [comment]
I think decreasing the nonprofit name font size and editing long nonprofit names (like the one pictured above) could be a solution.

**Comment by danford1** [comment]
In the image above, "dba" stands for "doing business as". It's not entirely necessary to show that in the project card; we can change `title` or `client` to display a short name on the project card and the full name on the project page. I think this is the only case where a nonprofit name goes to 3 lines with the current font size.

**Comment by designmatty** [comment]
Font size will only accomplish so much. Once we get to slightly smaller than macbook sized screens, the cards change size and we run into the issue again.

I'd say we'll make a design issue for it and fix it later. For now its passable.

**Pull request merged**
